version: "3.9"  # optional since v1.27.0
services:
  nami:
    build: $NAMI_PATH
    image: nami
    volumes:
      - build-volume:/nami/build
    tty: true
  local:
    build: .
    image: local-image
    volumes:
      - ./:/home/jovyan/work/
    ports:
      - 8000:8000
    command: ["./work/start.sh"]
  web-server:
    image: local-image
    volumes:
      - ./:/home/jovyan/work/
      - build-volume:/home/jovyan/nami
    ports:
      - 3000:8000
    command: ["python","-m","http.server"]

volumes:
  build-volume:    